[package]
name = "aurora-engine-modexp"
version = "1.2.0"
description = "Custom ModExp implementation that used in Aurora Engine"
keywords = ["modexp", "aurora", "engine"]
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
autobenches = false
publish = true

[dependencies]
hex.workspace = true
num.workspace = true
ibig = { workspace = true, optional = true }

[target.'cfg(all(target_os = "zkvm", target_vendor = "zisk"))'.dependencies]
cfg-if = "1.0"
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git", tag = "v0.13.0" }
# Local development
# ziskos = { path = "../../../zisk/ziskos/entrypoint" }

[lints]
workspace = true

[features]
default = ["std"]
std = ["num/std", "hex/std"]
bench = ["ibig"]
